### ISSUE TITLE
Extra `>> <<` chars appear in highlight.

### ISSUE THREAD

**Issue by robert-wallis** [WhiteHalmos/emailer#19]
In my emailer, I have a recipient name variable in the A column named something like `MOE` and the B column is `某某 Moe Mou`

However when that user gets an email, the HTML produced by this is like this:
`<span style="background-color:yellow">某某&gt;&gt; &lt;&lt;Moe Mou</span>`
Which is rendered as this in Gmail:
`某某>> <<Moe Mou`

This could also be related to the column B being a lookup into a different sheet.  But I think the API is returning the calculated value.
`=INDEX(Recipients!$B49, 1, 1)`
Just mentioning that in case that's the issue.

**Comment by WhiteHalmos** [comment]
Hmm... you are correct in that the api is currently returning the formatted/calculated value: https://github.com/WhiteHalmos/emailer/blob/master/emailer/fetcher.py#L11

It could be because the generated markdown is: `<<某某>> <<Moe Mou>>` and the regex is greedy: https://github.com/WhiteHalmos/emailer/blob/master/emailer/markdown.py#L16

The reason I didn't exclude `<` or `>` in the character class is to allow those characters to be in a highlight group too. One way to fix this is to figure out if both names are being highlighted switch highlighting to both, i.e. cause generated markdown to be `<<某某 Moe Mou>>`.

**Comment by robert-wallis** [comment]
Oh so, probably because I have two names:
MM, Moe Mou
MOE, 某某 Moe Mou

I’ll try getting rid of the first one.

**Comment by robert-wallis** [comment]
I just confirmed it is because I have two name shortcuts.  Nice catch!
